name: CI

on:
  push:
    paths:
      - 'modelling.py'
      - 'data/WA_Fn-UseC_-Telco-Customer-Churn_preprocessing.csv'
  pull_request:
    paths:
      - 'modelling.py'
      - 'data/WA_Fn-UseC_-Telco-Customer-Churn_preprocessing.csv'
  workflow_dispatch:

jobs:
  modelling-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ML pipeline
        run: python modelling.py

      - name: Upload MLflow artifacts and metrics
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-outputs
          path: |
            mlruns/
            metrics.json
