name: Run MLflow Project (CI)

on:
  push:
    branches:
      - main
    paths:
      - 'Workflow-CI/MLProject/WA_Fn-UseC_-Telco-Customer-Churn_preprocessing.csv'
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: MLProject/conda.yaml
        activate-environment: telco-env

    - name: Run MLflow Project
      run: |
        cd MLProject
        conda run -n telco-env python modelling.py

    - name: Upload mlruns artifact
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLProject/mlruns

    - name: Upload metrics artifact
      uses: actions/upload-artifact@v4
      with:
        name: metrics
        path: MLProject/metrics.json
